# Generated by Django 5.2.7 on 2025-12-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_subject_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(null=True, upload_to='lessons/%Y/%m'),
        ),
    ]
